name: Python application test with Github Actions

#on: [push]
on:
  schedule:
    - cron: "0 9,21 * * *"  # Runs at 9 AM and 9 PM UTC every day

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install dependencies
      run: |
        make install
    - name: Test with pytest
      run: |
        make test

    
    
