name: Run Makefile

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Makefile target to run'
        required: true

jobs:
  run_makefile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12  # Specify your desired Python version

    - name: Install dependencies
      run: |
        make install
    - name: Test with pytest
      run: |
        make test